= MEGA

Make End-of-the-month-process Great Again!

== Prerequisites

=== Google OAuth2 client setup

See link:https://developers.google.com/identity/protocols/OAuth2UserAgent[here] for a description how to setup a google oauth client.

== Dockerfiles

These are the Dockerfiles used by this project

* link:docker/agent-nodejs/Dockerfile[agent-nodejs/Dockerfile] +
 The Dockerfile for building the nodejs build agent
* link:docker/agent-quarkus/Dockerfile[agent-quarkus/Dockerfile] +
 The Dockerfile for building the quarkus build agent

== Openshift Dev Project

.Secrets
[source,bash]
----
# Create secrets
STAGE=[dev|prod|test] oc apps/ocp.sh createMegaSecrets
STAGE=[dev|prod|test] oc apps/ocp.sh createJenkinsSecrets

# Delete secrets
oc apps/ocp.sh deleteMegaSecrets
oc apps/ocp.sh deleteJenkinsSecrets

# Delete/Create secrets
STAGE=[dev|prod|test] oc apps/ocp.sh recreateMegaSecrets
STAGE=[dev|prod|test] oc apps/ocp.sh recreateJenkinsSecrets
----

.Build Configurations
[source,bash]
----
# Create all build configs
oc apps/ocp.sh createBuildConfigs

# Delete all build configs
oc apps/ocp.sh deleteBuildConfigs

# Delete/Create all build configs
oc apps/ocp.sh recreateBuildConfigs
----

.Jenkins
[source,bash]
----
# Create jenkins
oc apps/ocp.sh createJenkins

# Delete jenkins
oc apps/ocp.sh deleteJenkins

# Delete/Create jenkins
oc apps/ocp.sh recreateJenkins
----

IMPORTANT: Ensure that the properties in ``ocp/jenkins.properties`` and env vars in ``apps/ocp.sh`` are properly setup for your needs.

== Openshift Test/Prod Project

.Secrets
[source,bash]
----
oc create secret generic mega-secrets --from-file=filename=mega-secrets.properties
----

IMPORTANT: Ensure that the configuration is properly setup for your environment
