kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-pvc"
  annotations:
    openshift.io/display-name: "Jenkins PVC"
    description: "Jenkins PVC"
    iconClass: "icon-jenkins"
    tags: "jenkins"

parameters:
  - name: "JENKINS_SERVICE_NAME"
    displayName: "The jenkins service name"
    description: "The related jenkins service name"
    required: true

objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: "${JENKINS_SERVICE_NAME}"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi