kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-custom"
  annotations:
    openshift.io/display-name: "Jenkins slaves"
    description: "Jenkins slaves"
    iconClass: "icon-jenkins"
    tags: "jenkins"

parameters:
  - name: "JENKINS_SERVICE_NAME"
    required: true

  - name: "JENKINS_S2I_IMAGE"
    required: true

  - name: "JENKINS_IMAGE_STREAM_TAG"
    required: true
    
  - name: "GIT_URL"
    displayName: "Git url"
    description: "The git url of the repository holding the S2I resources"
    required: true

  - name: "GIT_REF"
    displayName: "Git ref"
    description: "The git ref of the repository holding the S2I resources"
    required: true

  - name: "GIT_SECRET"
    displayName: "Git source secret"
    description: "The git source secret for the checkout"
    required: true

  - name: "APP"
    displayName: "App label"
    description: "The value for the label app"
    required: true

objects:
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_NAME}-s2i"
      labels:
        app: "${APP}"
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: "${JENKINS_S2I_IMAGE}"

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_NAME}-custom"
      labels:
        app: "${APP}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${JENKINS_SERVICE_NAME}-custom"
    spec:
      source:  
        contextDir: "s2i/jenkins"                     
        git:
          uri: "${GIT_URL}"
          ref: "${GIT_REF}"
        sourceSecret:
            name: "${GIT_SECRET}"
        type: Git
      strategy:                     
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${JENKINS_SERVICE_NAME}-s2i:latest
        type: Source
      output:                       
        to:
          kind: ImageStreamTag
          name: ${JENKINS_IMAGE_STREAM_TAG}
      triggers:
        - type: "ImageChange" 
        - type: "ConfigChange"
          imageChange: {}